name       : python-unidecode
version    : 1.0.23
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/U/Unidecode/Unidecode-1.0.23.tar.gz : 8b85354be8fd0c0e10adbf0675f6dc2310e56fda43fa8fe049123b6c475e52fb
license    : GPL-2.0-or-later
component  : programming.python
summary    : ASCII transliterations of Unicode text
description: |
    This is a python port of Text::Unidecode Perl module. It provides a function, 'unidecode(...)' that takes Unicode data and tries to represent it in ASCII characters.
builddeps  :
    - python-setuptools
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
