name       : python-unidecode
version    : 1.3.4
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/U/Unidecode/Unidecode-1.3.4.tar.gz : 8e4352fb93d5a735c788110d2e7ac8e8031eb06ccbfe8d324ab71735015f9342
homepage   : https://pypi.org/project/Unidecode/
license    : GPL-2.0-or-later
component  : programming.python
summary    : ASCII transliterations of Unicode text
description: |
    This is a python port of Text::Unidecode Perl module. It provides a function, 'unidecode(...)' that takes Unicode data and tries to represent it in ASCII characters.
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
